; test.j

; Generated by ClassFileAnalyzer (Can)
; Analyzer and Disassembler for Java class files
; (Jasmin syntax 2, http://jasmin.sourceforge.net)
;
; ClassFileAnalyzer, version 0.7.0 


.bytecode 59.0
.source test.java
.class public test
.super java/lang/Object

.method public <init>()V
  .limit stack 1
  .limit locals 1
  .line 1
  0: aload_0
  1: invokespecial java/lang/Object/<init>()V
  4: return
.end method

.method public static check(I)Z
  .limit stack 2
  .limit locals 1
  .line 5
  0: iload_0
  1: iconst_2
  2: if_icmpne Label7
  .line 7
  5: iconst_1
  6: ireturn
Label7:
  .line 9
  7: iload_0
  8: iconst_3
  9: if_icmpne Label14
  .line 11
  12: iconst_0
  13: ireturn
Label14:
  .line 15
  14: iconst_0
  15: ireturn
  ; same_frame (frameNumber = 0)
  ; frame_type = 7, offset_delta = 7
  ; frame bytes: 7 
  .stack 
    offset 7
    .end stack
  ; same_frame (frameNumber = 1)
  ; frame_type = 6, offset_delta = 6
  ; frame bytes: 6 
  .stack 
    offset 14
    .end stack
.end method

.method public static main([Ljava/lang/String;)V
  .limit stack 0
  .limit locals 1
  .line 27
  0: return
.end method

